# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriellins/Downloads/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriellins/Downloads/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriellins/Downloads/trunk/CMakeFiles /home/gabriellins/Downloads/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriellins/Downloads/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eoserv-pch

# Build rule for target.
eoserv-pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eoserv-pch
.PHONY : eoserv-pch

# fast build rule for target.
eoserv-pch/fast:
	$(MAKE) -f CMakeFiles/eoserv-pch.dir/build.make CMakeFiles/eoserv-pch.dir/build
.PHONY : eoserv-pch/fast

#=============================================================================
# Target rules for targets named eoserv-pch-autogen

# Build rule for target.
eoserv-pch-autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eoserv-pch-autogen
.PHONY : eoserv-pch-autogen

# fast build rule for target.
eoserv-pch-autogen/fast:
	$(MAKE) -f CMakeFiles/eoserv-pch-autogen.dir/build.make CMakeFiles/eoserv-pch-autogen.dir/build
.PHONY : eoserv-pch-autogen/fast

#=============================================================================
# Target rules for targets named eoserv

# Build rule for target.
eoserv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eoserv
.PHONY : eoserv

# fast build rule for target.
eoserv/fast:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/build
.PHONY : eoserv/fast

tu/commands.o: tu/commands.cpp.o

.PHONY : tu/commands.o

# target to build an object file
tu/commands.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/commands.cpp.o
.PHONY : tu/commands.cpp.o

tu/commands.i: tu/commands.cpp.i

.PHONY : tu/commands.i

# target to preprocess a source file
tu/commands.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/commands.cpp.i
.PHONY : tu/commands.cpp.i

tu/commands.s: tu/commands.cpp.s

.PHONY : tu/commands.s

# target to generate assembly for a file
tu/commands.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/commands.cpp.s
.PHONY : tu/commands.cpp.s

tu/eoplus.o: tu/eoplus.cpp.o

.PHONY : tu/eoplus.o

# target to build an object file
tu/eoplus.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/eoplus.cpp.o
.PHONY : tu/eoplus.cpp.o

tu/eoplus.i: tu/eoplus.cpp.i

.PHONY : tu/eoplus.i

# target to preprocess a source file
tu/eoplus.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/eoplus.cpp.i
.PHONY : tu/eoplus.cpp.i

tu/eoplus.s: tu/eoplus.cpp.s

.PHONY : tu/eoplus.s

# target to generate assembly for a file
tu/eoplus.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/eoplus.cpp.s
.PHONY : tu/eoplus.cpp.s

tu/game_1.o: tu/game_1.cpp.o

.PHONY : tu/game_1.o

# target to build an object file
tu/game_1.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_1.cpp.o
.PHONY : tu/game_1.cpp.o

tu/game_1.i: tu/game_1.cpp.i

.PHONY : tu/game_1.i

# target to preprocess a source file
tu/game_1.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_1.cpp.i
.PHONY : tu/game_1.cpp.i

tu/game_1.s: tu/game_1.cpp.s

.PHONY : tu/game_1.s

# target to generate assembly for a file
tu/game_1.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_1.cpp.s
.PHONY : tu/game_1.cpp.s

tu/game_2.o: tu/game_2.cpp.o

.PHONY : tu/game_2.o

# target to build an object file
tu/game_2.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_2.cpp.o
.PHONY : tu/game_2.cpp.o

tu/game_2.i: tu/game_2.cpp.i

.PHONY : tu/game_2.i

# target to preprocess a source file
tu/game_2.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_2.cpp.i
.PHONY : tu/game_2.cpp.i

tu/game_2.s: tu/game_2.cpp.s

.PHONY : tu/game_2.s

# target to generate assembly for a file
tu/game_2.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_2.cpp.s
.PHONY : tu/game_2.cpp.s

tu/game_3.o: tu/game_3.cpp.o

.PHONY : tu/game_3.o

# target to build an object file
tu/game_3.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_3.cpp.o
.PHONY : tu/game_3.cpp.o

tu/game_3.i: tu/game_3.cpp.i

.PHONY : tu/game_3.i

# target to preprocess a source file
tu/game_3.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_3.cpp.i
.PHONY : tu/game_3.cpp.i

tu/game_3.s: tu/game_3.cpp.s

.PHONY : tu/game_3.s

# target to generate assembly for a file
tu/game_3.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/game_3.cpp.s
.PHONY : tu/game_3.cpp.s

tu/handlers.o: tu/handlers.cpp.o

.PHONY : tu/handlers.o

# target to build an object file
tu/handlers.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/handlers.cpp.o
.PHONY : tu/handlers.cpp.o

tu/handlers.i: tu/handlers.cpp.i

.PHONY : tu/handlers.i

# target to preprocess a source file
tu/handlers.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/handlers.cpp.i
.PHONY : tu/handlers.cpp.i

tu/handlers.s: tu/handlers.cpp.s

.PHONY : tu/handlers.s

# target to generate assembly for a file
tu/handlers.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/handlers.cpp.s
.PHONY : tu/handlers.cpp.s

tu/main.o: tu/main.cpp.o

.PHONY : tu/main.o

# target to build an object file
tu/main.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/main.cpp.o
.PHONY : tu/main.cpp.o

tu/main.i: tu/main.cpp.i

.PHONY : tu/main.i

# target to preprocess a source file
tu/main.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/main.cpp.i
.PHONY : tu/main.cpp.i

tu/main.s: tu/main.cpp.s

.PHONY : tu/main.s

# target to generate assembly for a file
tu/main.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/main.cpp.s
.PHONY : tu/main.cpp.s

tu/sha256.o: tu/sha256.c.o

.PHONY : tu/sha256.o

# target to build an object file
tu/sha256.c.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/sha256.c.o
.PHONY : tu/sha256.c.o

tu/sha256.i: tu/sha256.c.i

.PHONY : tu/sha256.i

# target to preprocess a source file
tu/sha256.c.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/sha256.c.i
.PHONY : tu/sha256.c.i

tu/sha256.s: tu/sha256.c.s

.PHONY : tu/sha256.s

# target to generate assembly for a file
tu/sha256.c.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/sha256.c.s
.PHONY : tu/sha256.c.s

tu/system.o: tu/system.cpp.o

.PHONY : tu/system.o

# target to build an object file
tu/system.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/system.cpp.o
.PHONY : tu/system.cpp.o

tu/system.i: tu/system.cpp.i

.PHONY : tu/system.i

# target to preprocess a source file
tu/system.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/system.cpp.i
.PHONY : tu/system.cpp.i

tu/system.s: tu/system.cpp.s

.PHONY : tu/system.s

# target to generate assembly for a file
tu/system.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/tu/system.cpp.s
.PHONY : tu/system.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... eoserv-pch"
	@echo "... install/strip"
	@echo "... eoserv-pch-autogen"
	@echo "... eoserv"
	@echo "... tu/commands.o"
	@echo "... tu/commands.i"
	@echo "... tu/commands.s"
	@echo "... tu/eoplus.o"
	@echo "... tu/eoplus.i"
	@echo "... tu/eoplus.s"
	@echo "... tu/game_1.o"
	@echo "... tu/game_1.i"
	@echo "... tu/game_1.s"
	@echo "... tu/game_2.o"
	@echo "... tu/game_2.i"
	@echo "... tu/game_2.s"
	@echo "... tu/game_3.o"
	@echo "... tu/game_3.i"
	@echo "... tu/game_3.s"
	@echo "... tu/handlers.o"
	@echo "... tu/handlers.i"
	@echo "... tu/handlers.s"
	@echo "... tu/main.o"
	@echo "... tu/main.i"
	@echo "... tu/main.s"
	@echo "... tu/sha256.o"
	@echo "... tu/sha256.i"
	@echo "... tu/sha256.s"
	@echo "... tu/system.o"
	@echo "... tu/system.i"
	@echo "... tu/system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

